### PR TITLE
Update to Unity Hub 1.6.1

### PR DESCRIPTION
**Pull request by ramcq**
Guessing that it's date co-incided with the release of Unity 2019.1. Unity
Editor for Linux Preview, yay!

### CODE REVIEW

**Comment by ramcq** [comment]
bot, build

**Comment by ramcq** [comment]
(The first build didn't work as flathub ran out of disk space.)

**Comment by ramcq** [comment]
Testing locally this works OK however!

**Comment by refi64** [comment]
Just ran a quick look, all the patches seem to still cleanly apply.

**Pull request merged**
