### PR TITLE
Revert "Update to 24.08 runtime"

### PR DESCRIPTION
**Pull request by wjt**
This reverts commit 3875d540db5f34aec026e3fcc1abc5417c8d55a2.

See https://github.com/flathub/com.unity.UnityHub/issues/127

### CODE REVIEW

**Comment by wjt** [comment]
@NoTuxNoBux Please could you test this once a test build is available?

**Comment by NoTuxNoBux** [comment]
Hmmm, looks like the link is dead now, maybe artifacts are only maintained for a limited amount of time. Is there any way I can regenerate the link?

Though I'm wondering if this technically should be reported somewhere upstream instead, since the 24.08 SDK worked fine up until last week. Either the SDK broke something or, if a normal package update broke UnityHub, chances are this will begin failing on non-Flatpak installations sooner or later as well.

**Comment by wjt** [comment]
Yes, test builds only last a day or two.

If you have the commit IDs for the working and non-working SDK builds, you could indeed report the problem to the SDK maintainers to try to understand what changed. The SDK is developed at https://gitlab.com/freedesktop-sdk/freedesktop-sdk

**Comment by NoTuxNoBux** [comment]
I reported it upstream [here](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1781).

Can also confirm that this Flatpak build seems to fix it. Maybe we should either wait a bit to see how they respond, or alternatively merge the downgrade to fix it for users and revert the downgrade in a new MR that can be left open until it's fixed (by the SDK or by Unity at some point)?

**Pull request merged**
