### PR TITLE
changed the TEMPDIR to one that is larger for unity

### LINKED ISSUE #47: Can't add new Unity installations
Before 2.4.1 I used this Flatpak version to install multiple Unity Editors and launch the Unity Hub with no problems whatsoever.
But with 2.4.1 I can't add new Unity Editors.
I have more than 500 GB of free disk space but it complains about not having enough free space.
Screenshot from 2020-10-15 18-20-59
Screenshot from 2020-10-15 18-21-03
What should I do? Please inform me if you need specific data about my specs.
```
OS: Linux Mint 20 x86_64 
Kernel: 5.4.0-51-generic 
Packages: 2306 (dpkg), 47 (flatpak) 
DE: Cinnamon 
WM: Mutter (Muffin) 
CPU: Intel i7-7500U (4) @ 3.500GHz 
GPU: NVIDIA GeForce 940MX 
Memory: 2660MiB / 15899MiB
``` 
Edit: corrected typo.

### PR DESCRIPTION
**Pull request by springbov**
Changed unity temp directory from XDG_RUNTIME_DIR to XDG_CACHE_HOME/tmp

Should resolve #47

### CODE REVIEW

**Comment by CDAGaming** [comment]
@springbov Could you rebase this onto master again for https://github.com/flathub/com.unity.UnityHub/commit/e36e63510d5000ef4e6b5111329fb67a60f4924d

Mainly so this can superseed #53 further (Even though #53 is incorrect due to metadata duplication)

**Comment by springbov** [comment]
@CDAGaming I think I did that right.

**Comment by refi64** [comment]
Thanks for this! I merged it by hand to keep the history a bit cleaner & avoid the merge commit.

**Comment by springbov** [comment]
@refi64 That's fine with me. Thanks for getting it in.

**Comment by CDAGaming** [comment]
Indeed! Glad to finally have this long-standing issue resolved 👍 

Also as for test cases, @springbov this worked perfectly as well, apologies for the late response

**Pull request closed without merging**
