### PR TITLE
Update runtime to 22.08

### PR DESCRIPTION
**Pull request by FakeShemp**

### CODE REVIEW

**Comment by refi64** [comment]
Ooc has this been tested to work yet? Just want to check since sometimes these update PRs get opened w/o testing it out...

**Comment by priahoud** [comment]
> Ooc has this been tested to work yet? Just want to check since sometimes these update PRs get opened w/o testing it out...

I just tested Runtime 22.08 in a local build and couldn't build to Android any more after the update.

It fails with
`No usable version of libssl was found`

Runtime 21.08
```
$ ldconfig -p | grep libssl
	libssl3.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl3.so
	libssl.so.1.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so.1.1
	libssl.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so
```

Runtime 22.08
```
$ ldconfig -p | grep libssl
	libssl3.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl3.so
	libssl.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so.3
	libssl.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so
```

So unfortunately, it seems that Unity still depends on an old version on libssl 1.1 and we have to postpone this PR until another solution emerges.

**Comment by AlfishSoftware** [comment]
> couldn't build to Android any more after the update.

Is this only for older Unity versions? From [this comment in that forum thread](https://forum.unity.com/threads/workaround-for-libssl-issue-on-ubuntu-22-04.1271405/#post-8730927):
> The problem doenst exist with Unity 2022.2.2.
> Works great on Ubuntu 22.04 with libssl3
> Unity 2021 doesnt work on same system because of libssl3

Would it not be possible to include OpenSSL 1.1 with this Flatpak somehow until the issue is solved upstream (if ever)?

It's quite annoying to be getting 4 warnings like these every time I `flatpak upgrade`:
```
Info: runtime org.freedesktop.[...] branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates.
   Please update to a supported runtime version.
Info: applications using this extension:
   com.unity.UnityHub
```

**Comment by wjt** [comment]
I pushed a commit to bundle libssl 1.1. 2021.3.32f1 seems to work. Once the new test build is complete, can someone who actually uses Unity routinely test whether the Android builds that were failing with the previous test build work with this one?

**Comment by wjt** [comment]
I'm getting this error when I try to compile a project for my Pixel 7 with 2021.3.32f1:

```
Execution failed for task ':launcher:packageRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.ide.common.signing.KeytoolException: Failed to read key AndroidDebugKey from store "/sysroot/home/wjt/.android/debug.keystore": Invalid keystore format
```

**Comment by wjt** [comment]
I deleted my entire `~/.android` directory after learning that the error above is typically secret code for “you have used a newer Android toolchain, with a newer Java version, that uses a backwards-incompatible keyring format”. Now I am able to deploy games to my Pixel 7 phone using both 2021 and 2022 editors and this branch of Unity Hub.

I will merge this PR in the next day or so unless someone reports it is broken in a way that the currently-published version is not. This gets us onto a supported runtime for another 9 months while figuring out the issue on #107.

**Comment by wjt** [comment]
Thank you for kicking this off, @FakeShemp – sorry it took 14 months to land.

**Pull request merged**
